"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: adk_llm_gateway.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdkLlmServiceClient = exports.AdkLlmServiceService = exports.ImageResponse = exports.ImageEditRequest = exports.ImageGenerateRequest = exports.EmbeddingResponse = exports.EmbeddingVector = exports.EmbeddingRequest = exports.GenerateContentResponse = exports.UsageMetadata = exports.GenerateContentRequest_PropertiesEntry = exports.GenerateContentRequest = exports.ToolDeclaration = exports.Content = exports.FileData = exports.InlineData = exports.FunctionResponse = exports.FunctionCall = exports.ContentPart = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
const grpc_js_1 = require("@grpc/grpc-js");
exports.protobufPackage = "phoenix.adk.v1";
function createBaseContentPart() {
    return {
        text: undefined,
        functionCall: undefined,
        functionResponse: undefined,
        inlineData: undefined,
        fileData: undefined,
        thought: false,
        thoughtSignature: undefined,
    };
}
exports.ContentPart = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.text !== undefined) {
            writer.uint32(10).string(message.text);
        }
        if (message.functionCall !== undefined) {
            exports.FunctionCall.encode(message.functionCall, writer.uint32(18).fork()).join();
        }
        if (message.functionResponse !== undefined) {
            exports.FunctionResponse.encode(message.functionResponse, writer.uint32(26).fork()).join();
        }
        if (message.inlineData !== undefined) {
            exports.InlineData.encode(message.inlineData, writer.uint32(34).fork()).join();
        }
        if (message.thought !== false) {
            writer.uint32(40).bool(message.thought);
        }
        if (message.thoughtSignature !== undefined) {
            writer.uint32(50).string(message.thoughtSignature);
        }
        if (message.fileData !== undefined) {
            exports.FileData.encode(message.fileData, writer.uint32(58).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseContentPart();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.text = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.functionCall = exports.FunctionCall.decode(reader, reader.uint32());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.functionResponse = exports.FunctionResponse.decode(reader, reader.uint32());
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.inlineData = exports.InlineData.decode(reader, reader.uint32());
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.thought = reader.bool();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.thoughtSignature = reader.string();
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.fileData = exports.FileData.decode(reader, reader.uint32());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            text: isSet(object.text) ? globalThis.String(object.text) : undefined,
            functionCall: isSet(object.functionCall)
                ? exports.FunctionCall.fromJSON(object.functionCall)
                : isSet(object.function_call)
                    ? exports.FunctionCall.fromJSON(object.function_call)
                    : undefined,
            functionResponse: isSet(object.functionResponse)
                ? exports.FunctionResponse.fromJSON(object.functionResponse)
                : isSet(object.function_response)
                    ? exports.FunctionResponse.fromJSON(object.function_response)
                    : undefined,
            inlineData: isSet(object.inlineData)
                ? exports.InlineData.fromJSON(object.inlineData)
                : isSet(object.inline_data)
                    ? exports.InlineData.fromJSON(object.inline_data)
                    : undefined,
            fileData: isSet(object.fileData)
                ? exports.FileData.fromJSON(object.fileData)
                : isSet(object.file_data)
                    ? exports.FileData.fromJSON(object.file_data)
                    : undefined,
            thought: isSet(object.thought)
                ? globalThis.Boolean(object.thought)
                : false,
            thoughtSignature: isSet(object.thoughtSignature)
                ? globalThis.String(object.thoughtSignature)
                : isSet(object.thought_signature)
                    ? globalThis.String(object.thought_signature)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.text !== undefined) {
            obj.text = message.text;
        }
        if (message.functionCall !== undefined) {
            obj.functionCall = exports.FunctionCall.toJSON(message.functionCall);
        }
        if (message.functionResponse !== undefined) {
            obj.functionResponse = exports.FunctionResponse.toJSON(message.functionResponse);
        }
        if (message.inlineData !== undefined) {
            obj.inlineData = exports.InlineData.toJSON(message.inlineData);
        }
        if (message.fileData !== undefined) {
            obj.fileData = exports.FileData.toJSON(message.fileData);
        }
        if (message.thought !== false) {
            obj.thought = message.thought;
        }
        if (message.thoughtSignature !== undefined) {
            obj.thoughtSignature = message.thoughtSignature;
        }
        return obj;
    },
    create(base) {
        return exports.ContentPart.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseContentPart();
        message.text = object.text ?? undefined;
        message.functionCall =
            object.functionCall !== undefined && object.functionCall !== null
                ? exports.FunctionCall.fromPartial(object.functionCall)
                : undefined;
        message.functionResponse =
            object.functionResponse !== undefined && object.functionResponse !== null
                ? exports.FunctionResponse.fromPartial(object.functionResponse)
                : undefined;
        message.inlineData =
            object.inlineData !== undefined && object.inlineData !== null
                ? exports.InlineData.fromPartial(object.inlineData)
                : undefined;
        message.fileData =
            object.fileData !== undefined && object.fileData !== null
                ? exports.FileData.fromPartial(object.fileData)
                : undefined;
        message.thought = object.thought ?? false;
        message.thoughtSignature = object.thoughtSignature ?? undefined;
        return message;
    },
};
function createBaseFunctionCall() {
    return { id: "", name: "", argsJson: "", thoughtSignature: undefined };
}
exports.FunctionCall = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.id !== "") {
            writer.uint32(10).string(message.id);
        }
        if (message.name !== "") {
            writer.uint32(18).string(message.name);
        }
        if (message.argsJson !== "") {
            writer.uint32(26).string(message.argsJson);
        }
        if (message.thoughtSignature !== undefined) {
            writer.uint32(34).string(message.thoughtSignature);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFunctionCall();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.name = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.argsJson = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.thoughtSignature = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            id: isSet(object.id) ? globalThis.String(object.id) : "",
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            argsJson: isSet(object.argsJson)
                ? globalThis.String(object.argsJson)
                : isSet(object.args_json)
                    ? globalThis.String(object.args_json)
                    : "",
            thoughtSignature: isSet(object.thoughtSignature)
                ? globalThis.String(object.thoughtSignature)
                : isSet(object.thought_signature)
                    ? globalThis.String(object.thought_signature)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.argsJson !== "") {
            obj.argsJson = message.argsJson;
        }
        if (message.thoughtSignature !== undefined) {
            obj.thoughtSignature = message.thoughtSignature;
        }
        return obj;
    },
    create(base) {
        return exports.FunctionCall.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFunctionCall();
        message.id = object.id ?? "";
        message.name = object.name ?? "";
        message.argsJson = object.argsJson ?? "";
        message.thoughtSignature = object.thoughtSignature ?? undefined;
        return message;
    },
};
function createBaseFunctionResponse() {
    return { id: "", name: "", responseJson: "", thoughtSignature: undefined };
}
exports.FunctionResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.id !== "") {
            writer.uint32(10).string(message.id);
        }
        if (message.name !== "") {
            writer.uint32(18).string(message.name);
        }
        if (message.responseJson !== "") {
            writer.uint32(26).string(message.responseJson);
        }
        if (message.thoughtSignature !== undefined) {
            writer.uint32(34).string(message.thoughtSignature);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFunctionResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.id = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.name = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.responseJson = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.thoughtSignature = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            id: isSet(object.id) ? globalThis.String(object.id) : "",
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            responseJson: isSet(object.responseJson)
                ? globalThis.String(object.responseJson)
                : isSet(object.response_json)
                    ? globalThis.String(object.response_json)
                    : "",
            thoughtSignature: isSet(object.thoughtSignature)
                ? globalThis.String(object.thoughtSignature)
                : isSet(object.thought_signature)
                    ? globalThis.String(object.thought_signature)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.id !== "") {
            obj.id = message.id;
        }
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.responseJson !== "") {
            obj.responseJson = message.responseJson;
        }
        if (message.thoughtSignature !== undefined) {
            obj.thoughtSignature = message.thoughtSignature;
        }
        return obj;
    },
    create(base) {
        return exports.FunctionResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFunctionResponse();
        message.id = object.id ?? "";
        message.name = object.name ?? "";
        message.responseJson = object.responseJson ?? "";
        message.thoughtSignature = object.thoughtSignature ?? undefined;
        return message;
    },
};
function createBaseInlineData() {
    return { mimeType: "", data: new Uint8Array(0) };
}
exports.InlineData = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.mimeType !== "") {
            writer.uint32(10).string(message.mimeType);
        }
        if (message.data.length !== 0) {
            writer.uint32(18).bytes(message.data);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseInlineData();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.mimeType = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.data = reader.bytes();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            mimeType: isSet(object.mimeType)
                ? globalThis.String(object.mimeType)
                : isSet(object.mime_type)
                    ? globalThis.String(object.mime_type)
                    : "",
            data: isSet(object.data)
                ? bytesFromBase64(object.data)
                : new Uint8Array(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.mimeType !== "") {
            obj.mimeType = message.mimeType;
        }
        if (message.data.length !== 0) {
            obj.data = base64FromBytes(message.data);
        }
        return obj;
    },
    create(base) {
        return exports.InlineData.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseInlineData();
        message.mimeType = object.mimeType ?? "";
        message.data = object.data ?? new Uint8Array(0);
        return message;
    },
};
function createBaseFileData() {
    return { mimeType: "", fileUri: "" };
}
exports.FileData = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.mimeType !== "") {
            writer.uint32(10).string(message.mimeType);
        }
        if (message.fileUri !== "") {
            writer.uint32(18).string(message.fileUri);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFileData();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.mimeType = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.fileUri = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            mimeType: isSet(object.mimeType)
                ? globalThis.String(object.mimeType)
                : isSet(object.mime_type)
                    ? globalThis.String(object.mime_type)
                    : "",
            fileUri: isSet(object.fileUri)
                ? globalThis.String(object.fileUri)
                : isSet(object.file_uri)
                    ? globalThis.String(object.file_uri)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.mimeType !== "") {
            obj.mimeType = message.mimeType;
        }
        if (message.fileUri !== "") {
            obj.fileUri = message.fileUri;
        }
        return obj;
    },
    create(base) {
        return exports.FileData.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFileData();
        message.mimeType = object.mimeType ?? "";
        message.fileUri = object.fileUri ?? "";
        return message;
    },
};
function createBaseContent() {
    return { role: "", parts: [] };
}
exports.Content = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.role !== "") {
            writer.uint32(10).string(message.role);
        }
        for (const v of message.parts) {
            exports.ContentPart.encode(v, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseContent();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.role = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.parts.push(exports.ContentPart.decode(reader, reader.uint32()));
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            role: isSet(object.role) ? globalThis.String(object.role) : "",
            parts: globalThis.Array.isArray(object?.parts)
                ? object.parts.map((e) => exports.ContentPart.fromJSON(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.role !== "") {
            obj.role = message.role;
        }
        if (message.parts?.length) {
            obj.parts = message.parts.map((e) => exports.ContentPart.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return exports.Content.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseContent();
        message.role = object.role ?? "";
        message.parts = object.parts?.map((e) => exports.ContentPart.fromPartial(e)) || [];
        return message;
    },
};
function createBaseToolDeclaration() {
    return { name: "", description: "", parametersJson: "" };
}
exports.ToolDeclaration = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.name !== "") {
            writer.uint32(10).string(message.name);
        }
        if (message.description !== "") {
            writer.uint32(18).string(message.description);
        }
        if (message.parametersJson !== "") {
            writer.uint32(26).string(message.parametersJson);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseToolDeclaration();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.name = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.description = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.parametersJson = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            description: isSet(object.description)
                ? globalThis.String(object.description)
                : "",
            parametersJson: isSet(object.parametersJson)
                ? globalThis.String(object.parametersJson)
                : isSet(object.parameters_json)
                    ? globalThis.String(object.parameters_json)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.description !== "") {
            obj.description = message.description;
        }
        if (message.parametersJson !== "") {
            obj.parametersJson = message.parametersJson;
        }
        return obj;
    },
    create(base) {
        return exports.ToolDeclaration.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseToolDeclaration();
        message.name = object.name ?? "";
        message.description = object.description ?? "";
        message.parametersJson = object.parametersJson ?? "";
        return message;
    },
};
function createBaseGenerateContentRequest() {
    return {
        model: "",
        empid: "",
        tenant: "",
        iaiTag: "",
        requestId: "",
        contents: [],
        systemInstruction: "",
        tools: [],
        temperature: undefined,
        maxOutputTokens: undefined,
        timeout: undefined,
        includeThoughts: undefined,
        thinkingBudget: undefined,
        thinkingLevel: undefined,
        reasoningEffort: undefined,
        topP: undefined,
        stopSequences: [],
        toolChoice: undefined,
        responseFormat: undefined,
        properties: {},
        token: undefined,
        messageId: undefined,
    };
}
exports.GenerateContentRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.model !== "") {
            writer.uint32(10).string(message.model);
        }
        if (message.empid !== "") {
            writer.uint32(18).string(message.empid);
        }
        if (message.tenant !== "") {
            writer.uint32(26).string(message.tenant);
        }
        if (message.iaiTag !== "") {
            writer.uint32(34).string(message.iaiTag);
        }
        if (message.requestId !== "") {
            writer.uint32(42).string(message.requestId);
        }
        for (const v of message.contents) {
            exports.Content.encode(v, writer.uint32(50).fork()).join();
        }
        if (message.systemInstruction !== "") {
            writer.uint32(58).string(message.systemInstruction);
        }
        for (const v of message.tools) {
            exports.ToolDeclaration.encode(v, writer.uint32(66).fork()).join();
        }
        if (message.temperature !== undefined) {
            writer.uint32(77).float(message.temperature);
        }
        if (message.maxOutputTokens !== undefined) {
            writer.uint32(80).int32(message.maxOutputTokens);
        }
        if (message.timeout !== undefined) {
            writer.uint32(93).float(message.timeout);
        }
        if (message.includeThoughts !== undefined) {
            writer.uint32(96).bool(message.includeThoughts);
        }
        if (message.thinkingBudget !== undefined) {
            writer.uint32(104).int32(message.thinkingBudget);
        }
        if (message.thinkingLevel !== undefined) {
            writer.uint32(114).string(message.thinkingLevel);
        }
        if (message.reasoningEffort !== undefined) {
            writer.uint32(122).string(message.reasoningEffort);
        }
        if (message.topP !== undefined) {
            writer.uint32(133).float(message.topP);
        }
        for (const v of message.stopSequences) {
            writer.uint32(138).string(v);
        }
        if (message.toolChoice !== undefined) {
            writer.uint32(146).string(message.toolChoice);
        }
        if (message.responseFormat !== undefined) {
            writer.uint32(154).string(message.responseFormat);
        }
        globalThis.Object.entries(message.properties).forEach(([key, value]) => {
            exports.GenerateContentRequest_PropertiesEntry.encode({ key: key, value }, writer.uint32(162).fork()).join();
        });
        if (message.token !== undefined) {
            writer.uint32(170).string(message.token);
        }
        if (message.messageId !== undefined) {
            writer.uint32(178).string(message.messageId);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGenerateContentRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.model = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.empid = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.tenant = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.iaiTag = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.requestId = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.contents.push(exports.Content.decode(reader, reader.uint32()));
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.systemInstruction = reader.string();
                    continue;
                }
                case 8: {
                    if (tag !== 66) {
                        break;
                    }
                    message.tools.push(exports.ToolDeclaration.decode(reader, reader.uint32()));
                    continue;
                }
                case 9: {
                    if (tag !== 77) {
                        break;
                    }
                    message.temperature = reader.float();
                    continue;
                }
                case 10: {
                    if (tag !== 80) {
                        break;
                    }
                    message.maxOutputTokens = reader.int32();
                    continue;
                }
                case 11: {
                    if (tag !== 93) {
                        break;
                    }
                    message.timeout = reader.float();
                    continue;
                }
                case 12: {
                    if (tag !== 96) {
                        break;
                    }
                    message.includeThoughts = reader.bool();
                    continue;
                }
                case 13: {
                    if (tag !== 104) {
                        break;
                    }
                    message.thinkingBudget = reader.int32();
                    continue;
                }
                case 14: {
                    if (tag !== 114) {
                        break;
                    }
                    message.thinkingLevel = reader.string();
                    continue;
                }
                case 15: {
                    if (tag !== 122) {
                        break;
                    }
                    message.reasoningEffort = reader.string();
                    continue;
                }
                case 16: {
                    if (tag !== 133) {
                        break;
                    }
                    message.topP = reader.float();
                    continue;
                }
                case 17: {
                    if (tag !== 138) {
                        break;
                    }
                    message.stopSequences.push(reader.string());
                    continue;
                }
                case 18: {
                    if (tag !== 146) {
                        break;
                    }
                    message.toolChoice = reader.string();
                    continue;
                }
                case 19: {
                    if (tag !== 154) {
                        break;
                    }
                    message.responseFormat = reader.string();
                    continue;
                }
                case 20: {
                    if (tag !== 162) {
                        break;
                    }
                    const entry20 = exports.GenerateContentRequest_PropertiesEntry.decode(reader, reader.uint32());
                    if (entry20.value !== undefined) {
                        message.properties[entry20.key] = entry20.value;
                    }
                    continue;
                }
                case 21: {
                    if (tag !== 170) {
                        break;
                    }
                    message.token = reader.string();
                    continue;
                }
                case 22: {
                    if (tag !== 178) {
                        break;
                    }
                    message.messageId = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            model: isSet(object.model) ? globalThis.String(object.model) : "",
            empid: isSet(object.empid) ? globalThis.String(object.empid) : "",
            tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
            iaiTag: isSet(object.iaiTag)
                ? globalThis.String(object.iaiTag)
                : isSet(object.iai_tag)
                    ? globalThis.String(object.iai_tag)
                    : "",
            requestId: isSet(object.requestId)
                ? globalThis.String(object.requestId)
                : isSet(object.request_id)
                    ? globalThis.String(object.request_id)
                    : "",
            contents: globalThis.Array.isArray(object?.contents)
                ? object.contents.map((e) => exports.Content.fromJSON(e))
                : [],
            systemInstruction: isSet(object.systemInstruction)
                ? globalThis.String(object.systemInstruction)
                : isSet(object.system_instruction)
                    ? globalThis.String(object.system_instruction)
                    : "",
            tools: globalThis.Array.isArray(object?.tools)
                ? object.tools.map((e) => exports.ToolDeclaration.fromJSON(e))
                : [],
            temperature: isSet(object.temperature)
                ? globalThis.Number(object.temperature)
                : undefined,
            maxOutputTokens: isSet(object.maxOutputTokens)
                ? globalThis.Number(object.maxOutputTokens)
                : isSet(object.max_output_tokens)
                    ? globalThis.Number(object.max_output_tokens)
                    : undefined,
            timeout: isSet(object.timeout)
                ? globalThis.Number(object.timeout)
                : undefined,
            includeThoughts: isSet(object.includeThoughts)
                ? globalThis.Boolean(object.includeThoughts)
                : isSet(object.include_thoughts)
                    ? globalThis.Boolean(object.include_thoughts)
                    : undefined,
            thinkingBudget: isSet(object.thinkingBudget)
                ? globalThis.Number(object.thinkingBudget)
                : isSet(object.thinking_budget)
                    ? globalThis.Number(object.thinking_budget)
                    : undefined,
            thinkingLevel: isSet(object.thinkingLevel)
                ? globalThis.String(object.thinkingLevel)
                : isSet(object.thinking_level)
                    ? globalThis.String(object.thinking_level)
                    : undefined,
            reasoningEffort: isSet(object.reasoningEffort)
                ? globalThis.String(object.reasoningEffort)
                : isSet(object.reasoning_effort)
                    ? globalThis.String(object.reasoning_effort)
                    : undefined,
            topP: isSet(object.topP)
                ? globalThis.Number(object.topP)
                : isSet(object.top_p)
                    ? globalThis.Number(object.top_p)
                    : undefined,
            stopSequences: globalThis.Array.isArray(object?.stopSequences)
                ? object.stopSequences.map((e) => globalThis.String(e))
                : globalThis.Array.isArray(object?.stop_sequences)
                    ? object.stop_sequences.map((e) => globalThis.String(e))
                    : [],
            toolChoice: isSet(object.toolChoice)
                ? globalThis.String(object.toolChoice)
                : isSet(object.tool_choice)
                    ? globalThis.String(object.tool_choice)
                    : undefined,
            responseFormat: isSet(object.responseFormat)
                ? globalThis.String(object.responseFormat)
                : isSet(object.response_format)
                    ? globalThis.String(object.response_format)
                    : undefined,
            properties: isObject(object.properties)
                ? globalThis.Object.entries(object.properties).reduce((acc, [key, value]) => {
                    acc[key] = globalThis.String(value);
                    return acc;
                }, {})
                : {},
            token: isSet(object.token) ? globalThis.String(object.token) : undefined,
            messageId: isSet(object.messageId)
                ? globalThis.String(object.messageId)
                : isSet(object.message_id)
                    ? globalThis.String(object.message_id)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.model !== "") {
            obj.model = message.model;
        }
        if (message.empid !== "") {
            obj.empid = message.empid;
        }
        if (message.tenant !== "") {
            obj.tenant = message.tenant;
        }
        if (message.iaiTag !== "") {
            obj.iaiTag = message.iaiTag;
        }
        if (message.requestId !== "") {
            obj.requestId = message.requestId;
        }
        if (message.contents?.length) {
            obj.contents = message.contents.map((e) => exports.Content.toJSON(e));
        }
        if (message.systemInstruction !== "") {
            obj.systemInstruction = message.systemInstruction;
        }
        if (message.tools?.length) {
            obj.tools = message.tools.map((e) => exports.ToolDeclaration.toJSON(e));
        }
        if (message.temperature !== undefined) {
            obj.temperature = message.temperature;
        }
        if (message.maxOutputTokens !== undefined) {
            obj.maxOutputTokens = Math.round(message.maxOutputTokens);
        }
        if (message.timeout !== undefined) {
            obj.timeout = message.timeout;
        }
        if (message.includeThoughts !== undefined) {
            obj.includeThoughts = message.includeThoughts;
        }
        if (message.thinkingBudget !== undefined) {
            obj.thinkingBudget = Math.round(message.thinkingBudget);
        }
        if (message.thinkingLevel !== undefined) {
            obj.thinkingLevel = message.thinkingLevel;
        }
        if (message.reasoningEffort !== undefined) {
            obj.reasoningEffort = message.reasoningEffort;
        }
        if (message.topP !== undefined) {
            obj.topP = message.topP;
        }
        if (message.stopSequences?.length) {
            obj.stopSequences = message.stopSequences;
        }
        if (message.toolChoice !== undefined) {
            obj.toolChoice = message.toolChoice;
        }
        if (message.responseFormat !== undefined) {
            obj.responseFormat = message.responseFormat;
        }
        if (message.properties) {
            const entries = globalThis.Object.entries(message.properties);
            if (entries.length > 0) {
                obj.properties = {};
                entries.forEach(([k, v]) => {
                    obj.properties[k] = v;
                });
            }
        }
        if (message.token !== undefined) {
            obj.token = message.token;
        }
        if (message.messageId !== undefined) {
            obj.messageId = message.messageId;
        }
        return obj;
    },
    create(base) {
        return exports.GenerateContentRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGenerateContentRequest();
        message.model = object.model ?? "";
        message.empid = object.empid ?? "";
        message.tenant = object.tenant ?? "";
        message.iaiTag = object.iaiTag ?? "";
        message.requestId = object.requestId ?? "";
        message.contents =
            object.contents?.map((e) => exports.Content.fromPartial(e)) || [];
        message.systemInstruction = object.systemInstruction ?? "";
        message.tools =
            object.tools?.map((e) => exports.ToolDeclaration.fromPartial(e)) || [];
        message.temperature = object.temperature ?? undefined;
        message.maxOutputTokens = object.maxOutputTokens ?? undefined;
        message.timeout = object.timeout ?? undefined;
        message.includeThoughts = object.includeThoughts ?? undefined;
        message.thinkingBudget = object.thinkingBudget ?? undefined;
        message.thinkingLevel = object.thinkingLevel ?? undefined;
        message.reasoningEffort = object.reasoningEffort ?? undefined;
        message.topP = object.topP ?? undefined;
        message.stopSequences = object.stopSequences?.map((e) => e) || [];
        message.toolChoice = object.toolChoice ?? undefined;
        message.responseFormat = object.responseFormat ?? undefined;
        message.properties = globalThis.Object.entries(object.properties ?? {}).reduce((acc, [key, value]) => {
            if (value !== undefined) {
                acc[key] = globalThis.String(value);
            }
            return acc;
        }, {});
        message.token = object.token ?? undefined;
        message.messageId = object.messageId ?? undefined;
        return message;
    },
};
function createBaseGenerateContentRequest_PropertiesEntry() {
    return { key: "", value: "" };
}
exports.GenerateContentRequest_PropertiesEntry = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.key !== "") {
            writer.uint32(10).string(message.key);
        }
        if (message.value !== "") {
            writer.uint32(18).string(message.value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGenerateContentRequest_PropertiesEntry();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            key: isSet(object.key) ? globalThis.String(object.key) : "",
            value: isSet(object.value) ? globalThis.String(object.value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.key !== "") {
            obj.key = message.key;
        }
        if (message.value !== "") {
            obj.value = message.value;
        }
        return obj;
    },
    create(base) {
        return exports.GenerateContentRequest_PropertiesEntry.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGenerateContentRequest_PropertiesEntry();
        message.key = object.key ?? "";
        message.value = object.value ?? "";
        return message;
    },
};
function createBaseUsageMetadata() {
    return {
        promptTokenCount: 0,
        candidatesTokenCount: 0,
        totalTokenCount: 0,
        cachedContentTokenCount: undefined,
        thoughtsTokenCount: undefined,
    };
}
exports.UsageMetadata = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.promptTokenCount !== 0) {
            writer.uint32(8).int32(message.promptTokenCount);
        }
        if (message.candidatesTokenCount !== 0) {
            writer.uint32(16).int32(message.candidatesTokenCount);
        }
        if (message.totalTokenCount !== 0) {
            writer.uint32(24).int32(message.totalTokenCount);
        }
        if (message.cachedContentTokenCount !== undefined) {
            writer.uint32(32).int32(message.cachedContentTokenCount);
        }
        if (message.thoughtsTokenCount !== undefined) {
            writer.uint32(40).int32(message.thoughtsTokenCount);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseUsageMetadata();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.promptTokenCount = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.candidatesTokenCount = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.totalTokenCount = reader.int32();
                    continue;
                }
                case 4: {
                    if (tag !== 32) {
                        break;
                    }
                    message.cachedContentTokenCount = reader.int32();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.thoughtsTokenCount = reader.int32();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            promptTokenCount: isSet(object.promptTokenCount)
                ? globalThis.Number(object.promptTokenCount)
                : isSet(object.prompt_token_count)
                    ? globalThis.Number(object.prompt_token_count)
                    : 0,
            candidatesTokenCount: isSet(object.candidatesTokenCount)
                ? globalThis.Number(object.candidatesTokenCount)
                : isSet(object.candidates_token_count)
                    ? globalThis.Number(object.candidates_token_count)
                    : 0,
            totalTokenCount: isSet(object.totalTokenCount)
                ? globalThis.Number(object.totalTokenCount)
                : isSet(object.total_token_count)
                    ? globalThis.Number(object.total_token_count)
                    : 0,
            cachedContentTokenCount: isSet(object.cachedContentTokenCount)
                ? globalThis.Number(object.cachedContentTokenCount)
                : isSet(object.cached_content_token_count)
                    ? globalThis.Number(object.cached_content_token_count)
                    : undefined,
            thoughtsTokenCount: isSet(object.thoughtsTokenCount)
                ? globalThis.Number(object.thoughtsTokenCount)
                : isSet(object.thoughts_token_count)
                    ? globalThis.Number(object.thoughts_token_count)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.promptTokenCount !== 0) {
            obj.promptTokenCount = Math.round(message.promptTokenCount);
        }
        if (message.candidatesTokenCount !== 0) {
            obj.candidatesTokenCount = Math.round(message.candidatesTokenCount);
        }
        if (message.totalTokenCount !== 0) {
            obj.totalTokenCount = Math.round(message.totalTokenCount);
        }
        if (message.cachedContentTokenCount !== undefined) {
            obj.cachedContentTokenCount = Math.round(message.cachedContentTokenCount);
        }
        if (message.thoughtsTokenCount !== undefined) {
            obj.thoughtsTokenCount = Math.round(message.thoughtsTokenCount);
        }
        return obj;
    },
    create(base) {
        return exports.UsageMetadata.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseUsageMetadata();
        message.promptTokenCount = object.promptTokenCount ?? 0;
        message.candidatesTokenCount = object.candidatesTokenCount ?? 0;
        message.totalTokenCount = object.totalTokenCount ?? 0;
        message.cachedContentTokenCount =
            object.cachedContentTokenCount ?? undefined;
        message.thoughtsTokenCount = object.thoughtsTokenCount ?? undefined;
        return message;
    },
};
function createBaseGenerateContentResponse() {
    return {
        content: undefined,
        turnComplete: false,
        partial: false,
        usageMetadata: undefined,
        errorCode: "",
        errorMessage: "",
        finishReason: undefined,
        rawResponseJson: undefined,
    };
}
exports.GenerateContentResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.content !== undefined) {
            exports.Content.encode(message.content, writer.uint32(10).fork()).join();
        }
        if (message.turnComplete !== false) {
            writer.uint32(16).bool(message.turnComplete);
        }
        if (message.partial !== false) {
            writer.uint32(24).bool(message.partial);
        }
        if (message.usageMetadata !== undefined) {
            exports.UsageMetadata.encode(message.usageMetadata, writer.uint32(34).fork()).join();
        }
        if (message.errorCode !== "") {
            writer.uint32(42).string(message.errorCode);
        }
        if (message.errorMessage !== "") {
            writer.uint32(50).string(message.errorMessage);
        }
        if (message.finishReason !== undefined) {
            writer.uint32(58).string(message.finishReason);
        }
        if (message.rawResponseJson !== undefined) {
            writer.uint32(66).string(message.rawResponseJson);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseGenerateContentResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.content = exports.Content.decode(reader, reader.uint32());
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.turnComplete = reader.bool();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }
                    message.partial = reader.bool();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.usageMetadata = exports.UsageMetadata.decode(reader, reader.uint32());
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.errorCode = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.errorMessage = reader.string();
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.finishReason = reader.string();
                    continue;
                }
                case 8: {
                    if (tag !== 66) {
                        break;
                    }
                    message.rawResponseJson = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            content: isSet(object.content)
                ? exports.Content.fromJSON(object.content)
                : undefined,
            turnComplete: isSet(object.turnComplete)
                ? globalThis.Boolean(object.turnComplete)
                : isSet(object.turn_complete)
                    ? globalThis.Boolean(object.turn_complete)
                    : false,
            partial: isSet(object.partial)
                ? globalThis.Boolean(object.partial)
                : false,
            usageMetadata: isSet(object.usageMetadata)
                ? exports.UsageMetadata.fromJSON(object.usageMetadata)
                : isSet(object.usage_metadata)
                    ? exports.UsageMetadata.fromJSON(object.usage_metadata)
                    : undefined,
            errorCode: isSet(object.errorCode)
                ? globalThis.String(object.errorCode)
                : isSet(object.error_code)
                    ? globalThis.String(object.error_code)
                    : "",
            errorMessage: isSet(object.errorMessage)
                ? globalThis.String(object.errorMessage)
                : isSet(object.error_message)
                    ? globalThis.String(object.error_message)
                    : "",
            finishReason: isSet(object.finishReason)
                ? globalThis.String(object.finishReason)
                : isSet(object.finish_reason)
                    ? globalThis.String(object.finish_reason)
                    : undefined,
            rawResponseJson: isSet(object.rawResponseJson)
                ? globalThis.String(object.rawResponseJson)
                : isSet(object.raw_response_json)
                    ? globalThis.String(object.raw_response_json)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.content !== undefined) {
            obj.content = exports.Content.toJSON(message.content);
        }
        if (message.turnComplete !== false) {
            obj.turnComplete = message.turnComplete;
        }
        if (message.partial !== false) {
            obj.partial = message.partial;
        }
        if (message.usageMetadata !== undefined) {
            obj.usageMetadata = exports.UsageMetadata.toJSON(message.usageMetadata);
        }
        if (message.errorCode !== "") {
            obj.errorCode = message.errorCode;
        }
        if (message.errorMessage !== "") {
            obj.errorMessage = message.errorMessage;
        }
        if (message.finishReason !== undefined) {
            obj.finishReason = message.finishReason;
        }
        if (message.rawResponseJson !== undefined) {
            obj.rawResponseJson = message.rawResponseJson;
        }
        return obj;
    },
    create(base) {
        return exports.GenerateContentResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGenerateContentResponse();
        message.content =
            object.content !== undefined && object.content !== null
                ? exports.Content.fromPartial(object.content)
                : undefined;
        message.turnComplete = object.turnComplete ?? false;
        message.partial = object.partial ?? false;
        message.usageMetadata =
            object.usageMetadata !== undefined && object.usageMetadata !== null
                ? exports.UsageMetadata.fromPartial(object.usageMetadata)
                : undefined;
        message.errorCode = object.errorCode ?? "";
        message.errorMessage = object.errorMessage ?? "";
        message.finishReason = object.finishReason ?? undefined;
        message.rawResponseJson = object.rawResponseJson ?? undefined;
        return message;
    },
};
function createBaseEmbeddingRequest() {
    return {
        model: "",
        empid: "",
        tenant: "",
        iaiTag: "",
        texts: [],
        token: undefined,
    };
}
exports.EmbeddingRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.model !== "") {
            writer.uint32(10).string(message.model);
        }
        if (message.empid !== "") {
            writer.uint32(18).string(message.empid);
        }
        if (message.tenant !== "") {
            writer.uint32(26).string(message.tenant);
        }
        if (message.iaiTag !== "") {
            writer.uint32(34).string(message.iaiTag);
        }
        for (const v of message.texts) {
            writer.uint32(42).string(v);
        }
        if (message.token !== undefined) {
            writer.uint32(50).string(message.token);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEmbeddingRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.model = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.empid = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.tenant = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.iaiTag = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.texts.push(reader.string());
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.token = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            model: isSet(object.model) ? globalThis.String(object.model) : "",
            empid: isSet(object.empid) ? globalThis.String(object.empid) : "",
            tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
            iaiTag: isSet(object.iaiTag)
                ? globalThis.String(object.iaiTag)
                : isSet(object.iai_tag)
                    ? globalThis.String(object.iai_tag)
                    : "",
            texts: globalThis.Array.isArray(object?.texts)
                ? object.texts.map((e) => globalThis.String(e))
                : [],
            token: isSet(object.token) ? globalThis.String(object.token) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.model !== "") {
            obj.model = message.model;
        }
        if (message.empid !== "") {
            obj.empid = message.empid;
        }
        if (message.tenant !== "") {
            obj.tenant = message.tenant;
        }
        if (message.iaiTag !== "") {
            obj.iaiTag = message.iaiTag;
        }
        if (message.texts?.length) {
            obj.texts = message.texts;
        }
        if (message.token !== undefined) {
            obj.token = message.token;
        }
        return obj;
    },
    create(base) {
        return exports.EmbeddingRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEmbeddingRequest();
        message.model = object.model ?? "";
        message.empid = object.empid ?? "";
        message.tenant = object.tenant ?? "";
        message.iaiTag = object.iaiTag ?? "";
        message.texts = object.texts?.map((e) => e) || [];
        message.token = object.token ?? undefined;
        return message;
    },
};
function createBaseEmbeddingVector() {
    return { values: [] };
}
exports.EmbeddingVector = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        writer.uint32(10).fork();
        for (const v of message.values) {
            writer.float(v);
        }
        writer.join();
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEmbeddingVector();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag === 13) {
                        message.values.push(reader.float());
                        continue;
                    }
                    if (tag === 10) {
                        const end2 = reader.uint32() + reader.pos;
                        while (reader.pos < end2) {
                            message.values.push(reader.float());
                        }
                        continue;
                    }
                    break;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            values: globalThis.Array.isArray(object?.values)
                ? object.values.map((e) => globalThis.Number(e))
                : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.values?.length) {
            obj.values = message.values;
        }
        return obj;
    },
    create(base) {
        return exports.EmbeddingVector.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEmbeddingVector();
        message.values = object.values?.map((e) => e) || [];
        return message;
    },
};
function createBaseEmbeddingResponse() {
    return { embeddings: [], errorCode: "", errorMessage: "" };
}
exports.EmbeddingResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        for (const v of message.embeddings) {
            exports.EmbeddingVector.encode(v, writer.uint32(10).fork()).join();
        }
        if (message.errorCode !== "") {
            writer.uint32(18).string(message.errorCode);
        }
        if (message.errorMessage !== "") {
            writer.uint32(26).string(message.errorMessage);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEmbeddingResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.embeddings.push(exports.EmbeddingVector.decode(reader, reader.uint32()));
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.errorCode = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.errorMessage = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            embeddings: globalThis.Array.isArray(object?.embeddings)
                ? object.embeddings.map((e) => exports.EmbeddingVector.fromJSON(e))
                : [],
            errorCode: isSet(object.errorCode)
                ? globalThis.String(object.errorCode)
                : isSet(object.error_code)
                    ? globalThis.String(object.error_code)
                    : "",
            errorMessage: isSet(object.errorMessage)
                ? globalThis.String(object.errorMessage)
                : isSet(object.error_message)
                    ? globalThis.String(object.error_message)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.embeddings?.length) {
            obj.embeddings = message.embeddings.map((e) => exports.EmbeddingVector.toJSON(e));
        }
        if (message.errorCode !== "") {
            obj.errorCode = message.errorCode;
        }
        if (message.errorMessage !== "") {
            obj.errorMessage = message.errorMessage;
        }
        return obj;
    },
    create(base) {
        return exports.EmbeddingResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEmbeddingResponse();
        message.embeddings =
            object.embeddings?.map((e) => exports.EmbeddingVector.fromPartial(e)) || [];
        message.errorCode = object.errorCode ?? "";
        message.errorMessage = object.errorMessage ?? "";
        return message;
    },
};
function createBaseImageGenerateRequest() {
    return {
        prompt: "",
        aspectRatio: "",
        empid: "",
        tenant: "",
        token: undefined,
    };
}
exports.ImageGenerateRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.prompt !== "") {
            writer.uint32(10).string(message.prompt);
        }
        if (message.aspectRatio !== "") {
            writer.uint32(18).string(message.aspectRatio);
        }
        if (message.empid !== "") {
            writer.uint32(26).string(message.empid);
        }
        if (message.tenant !== "") {
            writer.uint32(34).string(message.tenant);
        }
        if (message.token !== undefined) {
            writer.uint32(42).string(message.token);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseImageGenerateRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.prompt = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.aspectRatio = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.empid = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.tenant = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.token = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
            aspectRatio: isSet(object.aspectRatio)
                ? globalThis.String(object.aspectRatio)
                : isSet(object.aspect_ratio)
                    ? globalThis.String(object.aspect_ratio)
                    : "",
            empid: isSet(object.empid) ? globalThis.String(object.empid) : "",
            tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
            token: isSet(object.token) ? globalThis.String(object.token) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.prompt !== "") {
            obj.prompt = message.prompt;
        }
        if (message.aspectRatio !== "") {
            obj.aspectRatio = message.aspectRatio;
        }
        if (message.empid !== "") {
            obj.empid = message.empid;
        }
        if (message.tenant !== "") {
            obj.tenant = message.tenant;
        }
        if (message.token !== undefined) {
            obj.token = message.token;
        }
        return obj;
    },
    create(base) {
        return exports.ImageGenerateRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseImageGenerateRequest();
        message.prompt = object.prompt ?? "";
        message.aspectRatio = object.aspectRatio ?? "";
        message.empid = object.empid ?? "";
        message.tenant = object.tenant ?? "";
        message.token = object.token ?? undefined;
        return message;
    },
};
function createBaseImageEditRequest() {
    return {
        prompt: "",
        imageUrls: [],
        aspectRatio: "",
        empid: "",
        tenant: "",
        token: undefined,
    };
}
exports.ImageEditRequest = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.prompt !== "") {
            writer.uint32(10).string(message.prompt);
        }
        for (const v of message.imageUrls) {
            writer.uint32(18).string(v);
        }
        if (message.aspectRatio !== "") {
            writer.uint32(26).string(message.aspectRatio);
        }
        if (message.empid !== "") {
            writer.uint32(34).string(message.empid);
        }
        if (message.tenant !== "") {
            writer.uint32(42).string(message.tenant);
        }
        if (message.token !== undefined) {
            writer.uint32(50).string(message.token);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseImageEditRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.prompt = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.imageUrls.push(reader.string());
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.aspectRatio = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.empid = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.tenant = reader.string();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.token = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
            imageUrls: globalThis.Array.isArray(object?.imageUrls)
                ? object.imageUrls.map((e) => globalThis.String(e))
                : globalThis.Array.isArray(object?.image_urls)
                    ? object.image_urls.map((e) => globalThis.String(e))
                    : [],
            aspectRatio: isSet(object.aspectRatio)
                ? globalThis.String(object.aspectRatio)
                : isSet(object.aspect_ratio)
                    ? globalThis.String(object.aspect_ratio)
                    : "",
            empid: isSet(object.empid) ? globalThis.String(object.empid) : "",
            tenant: isSet(object.tenant) ? globalThis.String(object.tenant) : "",
            token: isSet(object.token) ? globalThis.String(object.token) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.prompt !== "") {
            obj.prompt = message.prompt;
        }
        if (message.imageUrls?.length) {
            obj.imageUrls = message.imageUrls;
        }
        if (message.aspectRatio !== "") {
            obj.aspectRatio = message.aspectRatio;
        }
        if (message.empid !== "") {
            obj.empid = message.empid;
        }
        if (message.tenant !== "") {
            obj.tenant = message.tenant;
        }
        if (message.token !== undefined) {
            obj.token = message.token;
        }
        return obj;
    },
    create(base) {
        return exports.ImageEditRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseImageEditRequest();
        message.prompt = object.prompt ?? "";
        message.imageUrls = object.imageUrls?.map((e) => e) || [];
        message.aspectRatio = object.aspectRatio ?? "";
        message.empid = object.empid ?? "";
        message.tenant = object.tenant ?? "";
        message.token = object.token ?? undefined;
        return message;
    },
};
function createBaseImageResponse() {
    return {
        success: false,
        imageData: "",
        service: "",
        usageJson: "",
        error: "",
    };
}
exports.ImageResponse = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.success !== false) {
            writer.uint32(8).bool(message.success);
        }
        if (message.imageData !== "") {
            writer.uint32(18).string(message.imageData);
        }
        if (message.service !== "") {
            writer.uint32(26).string(message.service);
        }
        if (message.usageJson !== "") {
            writer.uint32(34).string(message.usageJson);
        }
        if (message.error !== "") {
            writer.uint32(42).string(message.error);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseImageResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.success = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.imageData = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.service = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.usageJson = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 42) {
                        break;
                    }
                    message.error = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            success: isSet(object.success)
                ? globalThis.Boolean(object.success)
                : false,
            imageData: isSet(object.imageData)
                ? globalThis.String(object.imageData)
                : isSet(object.image_data)
                    ? globalThis.String(object.image_data)
                    : "",
            service: isSet(object.service) ? globalThis.String(object.service) : "",
            usageJson: isSet(object.usageJson)
                ? globalThis.String(object.usageJson)
                : isSet(object.usage_json)
                    ? globalThis.String(object.usage_json)
                    : "",
            error: isSet(object.error) ? globalThis.String(object.error) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.success !== false) {
            obj.success = message.success;
        }
        if (message.imageData !== "") {
            obj.imageData = message.imageData;
        }
        if (message.service !== "") {
            obj.service = message.service;
        }
        if (message.usageJson !== "") {
            obj.usageJson = message.usageJson;
        }
        if (message.error !== "") {
            obj.error = message.error;
        }
        return obj;
    },
    create(base) {
        return exports.ImageResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseImageResponse();
        message.success = object.success ?? false;
        message.imageData = object.imageData ?? "";
        message.service = object.service ?? "";
        message.usageJson = object.usageJson ?? "";
        message.error = object.error ?? "";
        return message;
    },
};
exports.AdkLlmServiceService = {
    generateContent: {
        path: "/phoenix.adk.v1.AdkLlmService/GenerateContent",
        requestStream: false,
        responseStream: true,
        requestSerialize: (value) => Buffer.from(exports.GenerateContentRequest.encode(value).finish()),
        requestDeserialize: (value) => exports.GenerateContentRequest.decode(value),
        responseSerialize: (value) => Buffer.from(exports.GenerateContentResponse.encode(value).finish()),
        responseDeserialize: (value) => exports.GenerateContentResponse.decode(value),
    },
    embed: {
        path: "/phoenix.adk.v1.AdkLlmService/Embed",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(exports.EmbeddingRequest.encode(value).finish()),
        requestDeserialize: (value) => exports.EmbeddingRequest.decode(value),
        responseSerialize: (value) => Buffer.from(exports.EmbeddingResponse.encode(value).finish()),
        responseDeserialize: (value) => exports.EmbeddingResponse.decode(value),
    },
    generateImage: {
        path: "/phoenix.adk.v1.AdkLlmService/GenerateImage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(exports.ImageGenerateRequest.encode(value).finish()),
        requestDeserialize: (value) => exports.ImageGenerateRequest.decode(value),
        responseSerialize: (value) => Buffer.from(exports.ImageResponse.encode(value).finish()),
        responseDeserialize: (value) => exports.ImageResponse.decode(value),
    },
    editImage: {
        path: "/phoenix.adk.v1.AdkLlmService/EditImage",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value) => Buffer.from(exports.ImageEditRequest.encode(value).finish()),
        requestDeserialize: (value) => exports.ImageEditRequest.decode(value),
        responseSerialize: (value) => Buffer.from(exports.ImageResponse.encode(value).finish()),
        responseDeserialize: (value) => exports.ImageResponse.decode(value),
    },
};
exports.AdkLlmServiceClient = (0, grpc_js_1.makeGenericClientConstructor)(exports.AdkLlmServiceService, "phoenix.adk.v1.AdkLlmService");
function bytesFromBase64(b64) {
    if (globalThis.Buffer) {
        return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
    }
    else {
        const bin = globalThis.atob(b64);
        const arr = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; ++i) {
            arr[i] = bin.charCodeAt(i);
        }
        return arr;
    }
}
function base64FromBytes(arr) {
    if (globalThis.Buffer) {
        return globalThis.Buffer.from(arr).toString("base64");
    }
    else {
        const bin = [];
        arr.forEach((byte) => {
            bin.push(globalThis.String.fromCharCode(byte));
        });
        return globalThis.btoa(bin.join(""));
    }
}
function isObject(value) {
    return typeof value === "object" && value !== null;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
//# sourceMappingURL=adk_llm_gateway.js.map